#!/usr/bin/python3
from libyui import ycpbuiltins
import sys, traceback
from dnsmanager.wizards import DNSSequence

if __name__ == "__main__":
    try:
        DNSSequence()
    except Exception as e:
        ycpbuiltins.y2error(str(e))
        ycpbuiltins.y2error(traceback.format_exc())

